site_name: humangas's cheat sheet
site_url: https://humangas.github.io/cheat/
repo_url: https://github.com/humangas/cheat/
repo_name: GitHub
site_description: humangas's cheat sheet
site_author: humangas
copyright: Copyright (c) 2018 humangas
google_analytics: ['UA-43176477-6', 'auto']
theme:
  name: 'material'
  language: 'ja'
docs_dir: '_docs'
site_dir: 'docs'
extra:
  search:
    language: 'jp'
