# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - add_ssh_keys:
          fingerprints:
            - "15:81:38:d4:e4:aa:29:e1:73:37:fc:db:56:56:39:ed"

      - run:
          name: make index
          command: make index

      - run:
          name: mkdocs build
          command: venv/bin/mkdocs build

      - run:
          name: update docs
          command: |
            git config --global user.name "humangas"
            git config --global user.email "humangas.net@gmail.com"
            if [ -n "$(git status --porcelain docs)" ]; then
                git add docs
                git commit -m "Updated docs by CircleCI (BUILD_NUM:$CIRCLE_BUILD_NUM) [skip ci]"
                git push origin master
            fi

